version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    image: docker-registry.metechvn.com/mock/client
    container_name: client
    ports:
      - "8888:80"

  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    image: docker-registry.metechvn.com/mock/server
    container_name: server
    ports:
      - "3333:3000"
      - "9090:9090"
    environment:
      - NODE_ENV=production
